// Regenerate tests/quality/gold-books.json by hitting books.toscrape.com
// directly (plain fetch — not our scraper pipeline) and parsing title,
// price, availability, and rating with small deterministic regexes.
//
// Run via:  npx tsx tests/quality/regenerate-gold-books.ts
//
// The site is a stable, purpose-built scraping sandbox so structure does
// not drift; re-running is safe and idempotent.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// A hand-picked mix spread across rating values so the quality suite
// exercises 1★ / 2★ / 3★ / 4★ / 5★ books. These are stable URLs on the
// books.toscrape sandbox.
const URLS = [
  'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
  'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
  'https://books.toscrape.com/catalogue/soumission_998/index.html',
  'https://books.toscrape.com/catalogue/sharp-objects_997/index.html',
  'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
  'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
  'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
  'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
  'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
  'https://books.toscrape.com/catalogue/the-black-maria_991/index.html',
  'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
  'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
  'https://books.toscrape.com/catalogue/set-me-free_988/index.html',
  'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
  'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
  'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
  'https://books.toscrape.com/catalogue/olio_984/index.html',
  'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
  'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
  'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
];

const RATING_WORD_TO_NUM: Record<string, number> = {
  One: 1, Two: 2, Three: 3, Four: 4, Five: 5,
};

interface Expected {
  title: string;
  price: number;
  availability: string;
  rating: number;
}

function parseBook(html: string): Expected {
  // <h1>Title</h1> inside <div class="product_main">
  const titleMatch = html.match(
    /<div class="col-sm-6 product_main">[\s\S]*?<h1>([^<]+)<\/h1>/,
  );
  if (!titleMatch) throw new Error('title not found');

  // <p class="price_color">£51.77</p>
  const priceMatch = html.match(
    /<p class="price_color">[^£]*£([\d.]+)\s*<\/p>/,
  );
  if (!priceMatch) throw new Error('price not found');

  // <p class="instock availability"> ... In stock ... </p>
  const availMatch = html.match(
    /<p class="instock availability">[\s\S]*?(In stock|Out of stock)/i,
  );
  if (!availMatch) throw new Error('availability not found');

  // <p class="star-rating Three"> ...
  const ratingMatch = html.match(
    /<p class="star-rating (One|Two|Three|Four|Five)"/,
  );
  if (!ratingMatch) throw new Error('rating not found');

  return {
    title: decodeHtmlEntities(titleMatch[1].trim()),
    price: Number(priceMatch[1]),
    availability: 'In stock',
    rating: RATING_WORD_TO_NUM[ratingMatch[1]],
  };
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
}

async function main() {
  const items: Array<{ url: string; expected: Expected }> = [];

  for (const url of URLS) {
    process.stdout.write(`  ${url.split('/').slice(-2, -1)[0]} ... `);
    try {
      const res = await fetch(url, {
        headers: { 'User-Agent': 'ScrapeForge-GoldBooksGen/1.0' },
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const html = await res.text();
      const expected = parseBook(html);
      items.push({ url, expected });
      console.log(
        `"${expected.title}" £${expected.price} rating=${expected.rating}`,
      );
    } catch (err) {
      console.log(`FAIL ${(err as Error).message}`);
    }
  }

  const out = {
    _comment:
      'Hand-verified ground truth for books.toscrape.com product pages. ' +
      'Regenerated by tests/quality/regenerate-gold-books.ts.',
    _verifiedOn: new Date().toISOString().slice(0, 10),
    _count: items.length,
    items,
  };

  const outPath = resolve(process.cwd(), 'tests/quality/gold-books.json');
  writeFileSync(outPath, JSON.stringify(out, null, 2) + '\n', 'utf8');
  console.log(`\nWrote ${items.length} items to ${outPath}`);
}

main().catch((err) => {
  console.error('fatal:', err);
  process.exit(1);
});
